# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 17:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.IntegerField(blank=True)),
                ('title', models.CharField(blank=True, max_length=100, unique=True)),
                ('contents', models.CharField(blank=True, max_length=500, unique=True)),
                ('link', models.URLField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='HH',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.IntegerField(blank=True)),
                ('title', models.CharField(blank=True, max_length=100, unique=True)),
                ('contents', models.CharField(blank=True, max_length=500, unique=True)),
                ('link', models.URLField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='HT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.IntegerField(blank=True)),
                ('title', models.CharField(blank=True, max_length=100, unique=True)),
                ('contents', models.CharField(blank=True, max_length=500, unique=True)),
                ('link', models.URLField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='KT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.IntegerField(blank=True)),
                ('title', models.CharField(blank=True, max_length=100, unique=True)),
                ('contents', models.CharField(blank=True, max_length=500, unique=True)),
                ('link', models.URLField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.IntegerField(blank=True)),
                ('title', models.CharField(blank=True, max_length=100, unique=True)),
                ('contents', models.CharField(blank=True, max_length=500, unique=True)),
                ('link', models.URLField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.IntegerField(blank=True)),
                ('title', models.CharField(blank=True, max_length=100, unique=True)),
                ('contents', models.CharField(blank=True, max_length=500, unique=True)),
                ('link', models.URLField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='NC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.IntegerField(blank=True)),
                ('title', models.CharField(blank=True, max_length=100, unique=True)),
                ('contents', models.CharField(blank=True, max_length=500, unique=True)),
                ('link', models.URLField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='OB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.IntegerField(blank=True)),
                ('title', models.CharField(blank=True, max_length=100, unique=True)),
                ('contents', models.CharField(blank=True, max_length=500, unique=True)),
                ('link', models.URLField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SK',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.IntegerField(blank=True)),
                ('title', models.CharField(blank=True, max_length=100, unique=True)),
                ('contents', models.CharField(blank=True, max_length=500, unique=True)),
                ('link', models.URLField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.IntegerField(blank=True)),
                ('title', models.CharField(blank=True, max_length=100, unique=True)),
                ('contents', models.CharField(blank=True, max_length=500, unique=True)),
                ('link', models.URLField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('nick_name', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='WO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.IntegerField(blank=True)),
                ('title', models.CharField(blank=True, max_length=100, unique=True)),
                ('contents', models.CharField(blank=True, max_length=500, unique=True)),
                ('link', models.URLField(blank=True, unique=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.Team')),
            ],
        ),
        migrations.AddField(
            model_name='ss',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.Team'),
        ),
        migrations.AddField(
            model_name='sk',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.Team'),
        ),
        migrations.AddField(
            model_name='ob',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.Team'),
        ),
        migrations.AddField(
            model_name='nc',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.Team'),
        ),
        migrations.AddField(
            model_name='lt',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.Team'),
        ),
        migrations.AddField(
            model_name='lg',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.Team'),
        ),
        migrations.AddField(
            model_name='kt',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.Team'),
        ),
        migrations.AddField(
            model_name='ht',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.Team'),
        ),
        migrations.AddField(
            model_name='hh',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.Team'),
        ),
        migrations.AddField(
            model_name='article',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.Team'),
        ),
    ]
