# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-12 16:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_ob'),
    ]

    operations = [
        migrations.CreateModel(
            name='NC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.IntegerField(blank=True)),
                ('title', models.CharField(blank=True, max_length=100, unique=True)),
                ('contents', models.CharField(blank=True, max_length=500, unique=True)),
                ('link', models.URLField(blank=True, unique=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.Team')),
            ],
        ),
    ]
