# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-10 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20170411_0240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='nick_name',
            field=models.CharField(max_length=5),
        ),
    ]
