# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-11 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20170411_0243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='contents',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
