# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 16:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hiterrank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.CharField(max_length=10)),
                ('avg', models.FloatField(default=0.0)),
                ('g', models.IntegerField(default=0)),
                ('pa', models.IntegerField(default=0)),
                ('ab', models.IntegerField(default=0)),
                ('r', models.IntegerField(default=0)),
                ('h', models.IntegerField(default=0)),
                ('two_base', models.IntegerField(default=0)),
                ('three_base', models.IntegerField(default=0)),
                ('hr', models.IntegerField(default=0)),
                ('total_base', models.IntegerField(default=0)),
                ('rbi', models.IntegerField(default=0)),
                ('sac', models.IntegerField(default=0)),
                ('sf', models.IntegerField(default=0)),
                ('bb', models.IntegerField(default=0)),
                ('ibb', models.IntegerField(default=0)),
                ('hbp', models.IntegerField(default=0)),
                ('so', models.IntegerField(default=0)),
                ('gdp', models.IntegerField(default=0)),
                ('slg', models.FloatField(default=0.0)),
                ('obp', models.FloatField(default=0.0)),
                ('ops', models.FloatField(default=0.0)),
                ('mh', models.IntegerField(default=0)),
                ('risp', models.FloatField(default=0.0)),
                ('ph_ba', models.FloatField(default=0.0)),
                ('standard_date', models.IntegerField(blank=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.Team')),
            ],
        ),
        migrations.CreateModel(
            name='Teamrank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(default=0)),
                ('win', models.IntegerField(default=0)),
                ('lose', models.IntegerField(default=0)),
                ('draw', models.IntegerField(default=0)),
                ('win_rate', models.FloatField(default=0.0)),
                ('game_gap', models.FloatField(default=0.0)),
                ('recent_10_game', models.CharField(blank=True, max_length=10)),
                ('continuous', models.CharField(blank=True, max_length=5)),
                ('home_score', models.CharField(blank=True, max_length=10)),
                ('away_score', models.CharField(blank=True, max_length=10)),
                ('standard_date', models.IntegerField(blank=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.Team')),
            ],
        ),
    ]
